# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constrains.xdc

# IP: ip/IP_clk_generator/IP_clk_generator.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP_clk_generator || ORIG_REF_NAME==IP_clk_generator} -quiet] -quiet

# XDC: ip/IP_clk_generator/IP_clk_generator_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==IP_clk_generator || ORIG_REF_NAME==IP_clk_generator} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/IP_clk_generator/IP_clk_generator.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==IP_clk_generator || ORIG_REF_NAME==IP_clk_generator} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/IP_clk_generator/IP_clk_generator_late.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==IP_clk_generator || ORIG_REF_NAME==IP_clk_generator} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/IP_clk_generator/IP_clk_generator_ooc.xdc
